# Generated by Django 4.1 on 2023-06-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
