# Generated by Django 4.1 on 2023-06-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_alter_alumno_date_created_alter_reserva_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
