# Generated by Django 4.1 on 2025-04-23 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('fechanacimiento', models.DateField()),
                ('disciplinasocio', models.CharField(max_length=25)),
                ('categoriasocio', models.CharField(max_length=25)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.domicilio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comunes',
            fields=[
                ('socios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.socios')),
            ],
            options={
                'abstract': False,
            },
            bases=('personas.socios',),
        ),
        migrations.CreateModel(
            name='Jubilados',
            fields=[
                ('socios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.socios')),
            ],
            options={
                'abstract': False,
            },
            bases=('personas.socios',),
        ),
        migrations.CreateModel(
            name='Menores',
            fields=[
                ('socios_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.socios')),
            ],
            options={
                'abstract': False,
            },
            bases=('personas.socios',),
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('fechanacimiento', models.DateField()),
                ('disciplinaprofesor', models.CharField(max_length=25)),
                ('categoriaprofesor', models.CharField(max_length=25)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.domicilio')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('fechanacimiento', models.DateField()),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.domicilio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('fechanacimiento', models.DateField()),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.domicilio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
