# Generated by Django 4.1 on 2025-04-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alertas_cuil_alertas_cvu_profesores_cuil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='deuda',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socios',
            name='socioactivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socios',
            name='valorcuota',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
