# Generated by Django 4.1 on 2025-04-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_socios_deuda_socios_socioactivo_socios_valorcuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracion',
            name='cuil',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administracion',
            name='cvu',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
