# Generated by Django 4.1 on 2025-04-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_administracion_cuil_administracion_cvu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administracion',
            options={'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='alertas',
            options={'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='comunes',
            options={'verbose_name_plural': 'Comunes'},
        ),
        migrations.AlterModelOptions(
            name='jubilados',
            options={'verbose_name_plural': 'Jubilados'},
        ),
        migrations.AlterModelOptions(
            name='menores',
            options={'verbose_name_plural': 'Menores'},
        ),
        migrations.AlterModelOptions(
            name='socios',
            options={'verbose_name_plural': 'Socios'},
        ),
        migrations.AddField(
            model_name='jubilados',
            name='descjubilados',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menores',
            name='descmenores',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
